---
- name: Gather System Facts
  hosts: all

- name: Install Datadog Agent
  hosts: all
  become: true
  roles:
    - Datadog.datadog

- name: Add datadog user to docker group.
  hosts: all
  become: true
  tasks:
    - user:
        name: "{{ datadog_user }}"
        groups: docker
        append: yes
