#!/usr/bin/env groovy

// set a version parameter that is latest
currentBuild.displayName = "${env.BUILD_NUMBER}:deploy:mario/gs-spring-boot-docker"

node('jenkins-slave') {

    stage('Checkout') {
      checkout scm
    }

    // dir ('./infrastructure/ansible/api') {
      
    //   stage('Deploy ECS') {
    //     // pull in ansible roles for github
    //     sh "ansible-galaxy install -r requirements.yml";
    //     // deploy ecs with different parameters based on env
    //     switch(env.JOB_NAME) {
    //       case 'mario-deploy':
    //       // deploy ecs if needed
    //       sh "ansible-playbook deploy-ecs.yml --extra-vars \"env=dev\"";
    //       break;
    //       default: sh "echo \"nothing to build\""
    //     }
    //   }

    //   stage('Deploy Service') {
    //   // service deploy different depending on environment job-name
    //     switch(env.JOB_NAME) {
    //       case 'mario-deploy':
    //       // deploy service
    //       sh "ansible-playbook deploy-service.yml --extra-vars \"env=dev\""; 
    //       break;
    //       default: sh "echo \"nothing to build\""
    //     }
    //   }
    // }

    stage('Deploy') {

      sh "ansible-galaxy install -r requirements.yml";
      
      ansiblePlaybook(
        playbook: './infrastructure/ansible/api/deploy.yml',
        extraVars: [
            env: 'dev'
        ])
    }
}
