#!/usr/bin/env groovy

// set a version parameter that is latest
currentBuild.displayName = "${env.BUILD_NUMBER}:deploy:mario/gs-spring-boot-docker"

node('jenkins-slave') {

    stage 'Checkout'
      checkout scm

    stage 'Deploy'

    dir ('./infrastructure/ansible/api') {
	// ansible deploy different depending on environment job-name
      sh "ansible-galaxy install -r requirements.yml";
      switch(env.JOB_NAME) {
        case 'mario-deploy':
        // deploy ecs if needed
        sh "ansible-playbook -vvvv deploy.yml --extra-vars \"env=dev service_state=absent\"";
        // deploy service
        sh "ansible-playbook -vvvv deploy.yml --extra-vars \"env=dev service_count=3\""; 
        break;
        default: sh "echo \"nothing to build\""
      }
    }
}

